spring:
  mail:
    username: q1470970746@163.com
    password: DVBDTMSWCNCQSZLM
    host: smtp.163.com

  datasource:
#    url: jdbc:mysql://localhost:3306/bill?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    url: jdbc:mysql://rm-bp1ned5wn038w35jd5o.mysql.rds.aliyuncs.com:3306/bill?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 123456
    password: Qzy070736
    username: root
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  level:
    com.simk.mapper: debug
server:
  port: 8089